invoice_date_override_settings:
  path: /invoice_date_override/settings
  methods: [ GET, POST ]
  defaults:
    _controller: 'Ebiggio\InvoiceDateOverride\Controller\BackOfficeSettings::index'
    _legacy_controller: 'BackOfficeSettings'
    _legacy_link: 'BackOfficeSettings'

admin_module_invoice_date_override_manual_override:
  path: /invoice_date_override/manual_override
  methods: [ POST ]
  defaults:
    _controller: 'Ebiggio\InvoiceDateOverride\Controller\ManualOverride::index'
    _legacy_controller: 'ManualOverride'
    _legacy_link: 'ManualOverride'