services:
  ebiggio.invoice_date_override.controller.back_office_settings:
    public: true
    class: Ebiggio\InvoiceDateOverride\Controller\BackOfficeSettings

  ebiggio.invoice_date_override.form.settings_form:
    public: true
    class: Ebiggio\InvoiceDateOverride\Form\SettingsFormType
    parent: 'form.type.translatable.aware'
    tags:
      - { name: form.type }

  ebiggio.invoice_date_override.form.settings_form_handler:
    public: true
    class: PrestaShop\PrestaShop\Core\Form\Handler
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@ebiggio.invoice_date_override.form.settings_data_provider'
      - 'Ebiggio\InvoiceDateOverride\Form\SettingsFormType'
      - 'Settings'

  ebiggio.invoice_date_override.form.settings_data_provider:
    public: true
    class: Ebiggio\InvoiceDateOverride\Form\SettingsDataProvider
    arguments:
      - '@ebiggio.invoice_date_override.form.settings_data_configuration'

  ebiggio.invoice_date_override.form.settings_data_configuration:
    public: true
    class: Ebiggio\InvoiceDateOverride\Form\SettingsDataConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'